-- Cria a tabela de respostas do onboarding
create table if not exists public.respostas_onboarding (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    nome_cliente text,
    empresa text,
    dados jsonb not null
);

-- Habilita o RLS (Row Level Security) na tabela
alter table public.respostas_onboarding enable row level security;

-- Cria uma política permitindo a inserção de dados por qualquer usuário (anônimo)
-- IMPORTANTE: Isso permite que os clientes preencham o formulário sem precisar fazer login.
create policy "Permitir inserções anônimas"
on public.respostas_onboarding
for insert
to anon
with check (true);

-- (Opcional) Cria uma política para que apenas usuários autenticados (como você) possam visualizar as respostas no dashboard
create policy "Permitir leitura apenas para autenticados"
on public.respostas_onboarding
for select
to authenticated
using (true);
